version: "3.2"
services:
  rabbitmq-tf:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq-tf'
    deploy:
      resources:
        limits:
          memory: 500M  # 50MB
        reservations:
          memory: 100M
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge