version: '3.2'
services:

  kafka-tf:
    image: bitnami/kafka:latest
    container_name: 'kafka-tf'
    deploy:
      resources:
        limits:
          memory: 500M  # 50MB
        reservations:
          memory: 100M
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper-tf
    networks:
      - kafka_go_net
    links:
      - zookeeper-tf:zookeeper

  zookeeper-tf:
    container_name: 'zookeeper-tf'
    image: bitnami/zookeeper:latest
    deploy:
      resources:
        limits:
          memory: 500M  # 50MB
        reservations:
          memory: 100M
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafka_go_net

networks:
  kafka_go_net:
    driver: bridge

